# Generated by Django 6.1 on 2026-08-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(help_text='النص الخام أو المعالج الذي أرسله الطالب أو ولي الأمر.', verbose_name='استعلام المستخدم')),
                ('response', models.TextField(help_text='الرد النهائي المنسق بلغة Markdown الذي تم إرجاعه للمستخدم.', verbose_name='رد النظام')),
                ('intent_detected', models.CharField(help_text='النية التصنيفية المستخرجة بواسطة محرك الـ NLP (مثل query_schedule).', max_length=100, verbose_name='النية المكتشفة')),
                ('confidence_score', models.FloatField(default=0.0, help_text='درجة الثقة في دقة تحليل الاستعلام وتتراوح بين 0.0 و 1.0.', verbose_name='نسبة الثقة')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='التاريخ والوقت الذي تم فيه تنفيذ الاستعلام وتخزينه.', verbose_name='وقت الاستعلام')),
            ],
            options={
                'verbose_name': 'سجل محادثة',
                'verbose_name_plural': 'سجلات المحادثات',
                'ordering': ['-created_at'],
            },
        ),
    ]
