# Generated by Django 4.2.30 on 2026-09-06 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant_api', '0002_alter_chatlog_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(help_text='نص الاستعلام الأصلي الذي تم تقييم رده.', verbose_name='الاستعلام')),
                ('response', models.TextField(help_text='نص الرد الذي تم تقييمه من قبل المستخدم.', verbose_name='الرد')),
                ('is_positive', models.BooleanField(help_text='True إذا كان التقييم إيجابياً (👍)، False إذا كان سلبياً (👎).', verbose_name='تقييم إيجابي')),
                ('session_id', models.CharField(blank=True, default='', max_length=64, verbose_name='معرف الجلسة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت التقييم')),
            ],
            options={
                'verbose_name': 'تقييم',
                'verbose_name_plural': 'التقييمات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='chatlog',
            name='response_time_ms',
            field=models.IntegerField(default=0, help_text='الزمن المستغرق لمعالجة الاستعلام وإنتاج الرد بالمللي ثانية.', verbose_name='زمن الاستجابة (ملي ثانية)'),
        ),
        migrations.AddField(
            model_name='chatlog',
            name='session_id',
            field=models.CharField(blank=True, default='', help_text='معرف فريد لجلسة المستخدم لتتبع المحادثات المتسلسلة.', max_length=64, verbose_name='معرف الجلسة'),
        ),
        migrations.AlterField(
            model_name='chatlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
